package com.tma.movemind.ui.fragment_search_videos.helper_installer

object SEARCH_INDEX {
    val INDEX_BRANDS = 0
    val INDEX_MAIN_OPTIONS = INDEX_BRANDS + 1

    val INDEX_COLLECTIONS = 10
    val INDEX_DURATIONS_OF_COLLECTION = INDEX_COLLECTIONS + 1
    val INDEX_INSTRUCTORS_OF_COLLECTION = INDEX_DURATIONS_OF_COLLECTION + 1
    val INDEX_LEVELS_OF_COLLECTION = INDEX_INSTRUCTORS_OF_COLLECTION + 1

    val INDEX_DURATIONS = INDEX_COLLECTIONS * 2
    val INDEX_COLLECTIONS_OF_DURATION = INDEX_DURATIONS + 1

    val INDEX_INSTRUCTORS = INDEX_DURATIONS * 2
    val INDEX_COLLECTIONS_OF_INSTRUCTOR = INDEX_INSTRUCTORS + 1

    val INDEX_LEVELS = INDEX_INSTRUCTORS * 2
    val INDEX_COLLECTIONS_OF_LEVEL = INDEX_LEVELS + 1
}